name: Compilación y pruebas c#
on: push
jobs:
  Compilacion:
    runs-on: ubuntu-latest
    environment: PRUEBAS
    steps:
      - run: echo "El secreto es ${{ secrets.GOOGLE_TOKEN }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Instalamos dependencia de NET
        run: dotnet restore      
      - name: Compilamos
        run: dotnet build
      - name: Ejecutamos las pruebas
        run: dotnet test
      - name: Publicar un release
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: Nuevo Release
      
