name: Compilación y pruebas c#
on: push
jobs:
  Compilacion:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compilamos
        run: dotnet build
      - name: Ejecutamos las pruebas
        run: donet test
      
